name: Provision GCP infrastructure

on:
  push:
    branches:
      - main
    paths:
      - "terraform/app/**"
  workflow_dispatch:

env:
  TF_APP_WORKDIR: terraform/app

jobs:
  terraform-plan:
    name: "Terraform plan"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_APP_WORKDIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.PROVIDER_NAME }}
          service_account: ${{ secrets.SA_EMAIL }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Terraform test
        run: terraform test
      - name: Terraform Plan
        run: terraform plan -out=terraform.tfplan
        env:
          TF_VAR_sql_user_password: ${{ secrets.DB_PASSWORD }}
      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ env.TF_APP_WORKDIR }}/terraform.tfplan

  terraform-apply:
    name: "Terraform apply"
    runs-on: ubuntu-latest
    needs: terraform-plan
    permissions:
      contents: "read"
      id-token: "write"
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_APP_WORKDIR }}
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ${{ env.TF_APP_WORKDIR }}
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.PROVIDER_NAME }}
          service_account: ${{ secrets.SA_EMAIL }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve terraform.tfplan
        env:
          TF_VAR_sql_user_password: ${{ secrets.DB_PASSWORD }}
